#!/bin/sh
### BEGIN INIT INFO
# Provides:          nftables
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nftables firewall
### END INIT INFO

RULESET="/etc/nftables.nft"

case "$1" in
    start)
        echo "Loading nftables ruleset..."
        if [ -f "$RULESET" ]; then
            /usr/sbin/nft -f "$RULESET"
        fi
        ;;
    stop)
        echo "Flushing nftables ruleset..."
        /usr/sbin/nft flush ruleset
        ;;
    restart) "$0" stop; "$0" start ;;
    status)
        if /usr/sbin/nft list ruleset 2>/dev/null | grep -q .; then
            echo "nftables ruleset is loaded"
        else
            echo "nftables ruleset is empty or not loaded"
            exit 1
        fi
        ;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
