# ============================================================
# DHCP 全局选项
# ============================================================
# 设置为权威 DHCP 服务器，加快局域网设备获取 IP 的速度
dhcp-authoritative

# 租约记录文件位置
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
